spring:
  application:
    name: "payments-service"
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: localhost
      port: 27017
      database: pagamentos_db
      username: admin
      password: admin

server:
  port: 8081